name       : granite
version    : 5.5.0
release    : 20
source     :
    - https://github.com/elementary/granite/archive/5.5.0.tar.gz : 0c376520c7d462fca05213a14970ee1075fea4a78062a33b47529e2647cd5557
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
