name       : granite
version    : 5.3.0
release    : 17
source     :
    - https://github.com/elementary/granite/archive/5.3.0.tar.gz : c3bc3a884e78764dcc41dd7a9a3b4f3489d2cd103b8c664c0357b2d6236e17ed
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
