name       : granite
version    : '0.5'
release    : 7
source     :
    - https://github.com/elementary/granite/archive/0.5.tar.gz : cc4905ae70fddeba3d2ded44bb642be77d419aa090251a7ab24c155b8616be06
license    : LGPL-3.0
component  : programming
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
