name       : granite
version    : 5.4.0
release    : 18
source     :
    - https://github.com/elementary/granite/archive/5.4.0.tar.gz : 8194031cac3b87d84a3fab9c30270485ce73f8b8ec23f26c9152b6859c8a18fd
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
