name       : granite
version    : 5.2.3
release    : 15
source     :
    - https://github.com/elementary/granite/archive/5.2.3.tar.gz : 6ff86a90896690d25016e80e5192f87f6e9045e35ccc1db4747b92086d9b492f
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Fall-back-to-org.gnome.desktop.interface-if-wingpane.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
