name       : granite
version    : 6.2.0
release    : 21
source     :
    - https://github.com/elementary/granite/archive/refs/tags/6.2.0.tar.gz : 067d31445da9808a802fca523630c3e4b84d2d7c78ae547ced017cb7f3b9c6b5
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
