name       : granite
version    : 5.2.2
release    : 12
source     :
    - https://github.com/elementary/granite/archive/5.2.2.tar.gz : a2bfb717570b2b7ffef8715fae0dcabe7e3de21f6cb9392f1184a57ae6436f6c
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %patch -p1 < $pkgfiles/0001-Revert-upstream-breakage-due-to-schema-change.patch
    %cmake .
build      : |
    %make
install    : |
    %make_install
