name        : granite
version     : 0.4.0.1
release     : 4
source     :
    - https://launchpad.net/granite/0.4/0.4.0.1/+download/granite-0.4.0.1.tar.xz : 95a142a8befeedc35a089d638e759b657905508dc3007036d6c1fa3efe94c4dd
license     : LGPL-3.0
summary     : elementary Development Library/Framework
component   : programming
builddeps   :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
description : |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
