name        : granite
version     : 0.3.1
release     : 3
source     :
    - https://launchpad.net/granite/0.3/0.3.1/+download/granite-0.3.1.tar.xz : 8ec1d61f9aba75f1b3a745e721288b0dfb34cb11d1307be80cef7b0571c2dec6
license     : LGPL-3.0
summary     : elementary Development Library/Framework
builddeps   :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
description : |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
