name       : granite
version    : '5.0'
release    : 9
source     :
    - https://github.com/elementary/granite/archive/5.0.tar.gz : 62dd9a8ddef61d42bb77fdc6626e235d3129bd438533a1575652f7a15fd186c8
license    : LGPL-3.0-or-later
component  : programming.library
summary    : elementary Development Library/Framework
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
