name       : granite
version    : 0.4.1
release    : 5
source     :
    - https://github.com/elementary/granite/archive/0.4.1.tar.gz : 035a9b36ef73352ff8a76be06b876d9e2ea6633abb693fb67297d998c8d3a240
license    : LGPL-3.0
summary    : elementary Development Library/Framework
component  : programming
builddeps  :
    - pkgconfig(gee-0.8)
    - pkgconfig(gtk+-3.0)
    - vala
description: |
    An extension to GTK+ that provides several useful widgets and classes to ease application development.
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
